version: '4.5'

services:
  codecat:
    build: .
    ports:
      - "15356:80"
    env_file:
      - path: .env
        required: true
    environment:
      - FLASK_SERVER_NAME="localhost:15356"
    volumes:
      - codecat-data:/app/.data

volumes:
  codecat-data: