version: '4.5'

services:
  codecat:
    build: .
    ports:
      - "15356:80"
    env_file:
      - path: .env
        required: true
    volumes:
      - codecat-data:/app/.data

volumes:
  codecat-data: